// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class Exercise1Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() throws MalformedURLException {
    driver = new RemoteWebDriver(new URL("http://localhost:4444/wd/hub"), DesiredCapabilities.chrome());
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void exercise1() {
    // Test name: Exercise1
    // Step # | name | target | value
    // 1 | open | https://demo.opencart.com/index.php?route=account/register&language=en-gb | 
    driver.get("https://demo.opencart.com/index.php?route=account/register&language=en-gb");
    // 2 | setWindowSize | 1296x688 | 
    driver.manage().window().setSize(new Dimension(1296, 688));
    // 3 | click | id=input-firstname | 
    driver.findElement(By.id("input-firstname")).click();
    // 4 | click | id=input-firstname | 
    driver.findElement(By.id("input-firstname")).click();
    // 5 | type | id=input-firstname | Mink
    driver.findElement(By.id("input-firstname")).sendKeys("Mink");
    // 6 | click | id=input-lastname | 
    driver.findElement(By.id("input-lastname")).click();
    // 7 | type | id=input-lastname | Lynn
    driver.findElement(By.id("input-lastname")).sendKeys("Lynn");
    // 8 | click | id=input-email | 
    driver.findElement(By.id("input-email")).click();
    // 9 | type | id=input-email | ex@gmail.com
    driver.findElement(By.id("input-email")).sendKeys("ex@gmail.com");
    // 10 | click | id=input-password | 
    driver.findElement(By.id("input-password")).click();
    // 11 | type | id=input-password | 1234
    driver.findElement(By.id("input-password")).sendKeys("1234");
    // 12 | click | name=agree | 
    driver.findElement(By.name("agree")).click();
    // 13 | click | css=.btn-primary | 
    driver.findElement(By.cssSelector(".btn-primary")).click();
  }
}
